// Auto-generated by scripts/generate-icons.js
// Do not edit manually

export const ICON_MAP: Record<string, string> = {
  "chat": "💬",
  "agents": "🤖",
  "tasks": "📋",
  "memory": "🧬",
  "logs": "📝",
  "settings": "⚙️",
  "notifications": "🔔",
  "send": "↑",
  "microphone": "🎤",
  "refresh": "↻",
  "menu": "☰",
  "home": "🏠",
  "planner": "🧠",
  "coding": "💻",
  "research": "🔍",
  "execution": "⚡",
  "search": "🔎",
  "clear": "✕",
  "back": "←",
  "check": "✓",
  "warning": "⚠️",
  "error": "❌",
  "success": "✅",
  "pending": "⏳",
  "running": "🔄",
  "tool": "🔧",
  "thought": "💭",
  "star": "⭐"
};

export type IconName = keyof typeof ICON_MAP;
export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];
