#!/usr/bin/env node
// ============================================================
// AgentOS — Icon Generator Script
// Generates the emoji-based icon map for the mobile app.
// Usage: node scripts/generate-icons.js
// ============================================================

const fs = require('fs');
const path = require('path');

const ICONS = {
  chat: '💬',
  agents: '🤖',
  tasks: '📋',
  memory: '🧬',
  logs: '📝',
  settings: '⚙️',
  notifications: '🔔',
  send: '↑',
  microphone: '🎤',
  refresh: '↻',
  menu: '☰',
  home: '🏠',
  planner: '🧠',
  coding: '💻',
  research: '🔍',
  execution: '⚡',
  search: '🔎',
  clear: '✕',
  back: '←',
  check: '✓',
  warning: '⚠️',
  error: '❌',
  success: '✅',
  pending: '⏳',
  running: '🔄',
  tool: '🔧',
  thought: '💭',
  star: '⭐',
};

const outputDir = path.join(__dirname, '..', 'components', 'icons');

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Generate index file
const indexContent = `// Auto-generated by scripts/generate-icons.js
// Do not edit manually

export const ICON_MAP: Record<string, string> = ${JSON.stringify(ICONS, null, 2)};

export type IconName = keyof typeof ICON_MAP;
export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];
`;

fs.writeFileSync(path.join(outputDir, 'iconMap.ts'), indexContent);

console.log(`✅ Generated ${Object.keys(ICONS).length} icons → components/icons/iconMap.ts`);
console.log(`   Available icons: ${Object.keys(ICONS).join(', ')}`);
